name: simple-ci

on:
  push:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Job1 message
        run: echo "job1 started"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Job2 message
        run: echo "job2 started"
